[정수론] 0901
Altu-Bitu-7/Altu-Bitu-KangMina pull request #3
Opened 2024-09-01 13:51 UTC by minae-mina

### 인적사항
학번: 1976002
이름: 강민아
</br>

### 과제제출
기존 제출: 1735, 2840, 6588, 9421
추가 제출: 
</br>

2024-09-08 04:13 UTC, avocado8 approved these changes
p3(6588)
민아님 안녕하세요 :3 필수6588번 코드리뷰 드렸습니다.
도전 문제까지 풀어주시다니 멋져요!
간단한 코멘트 올려드렸고 질문이 있으시다면 언제든 리뷰어를 호출해주세용 :)

2024-09-08 04:13 UTC, avocado8 commented on 03_정수론/필수/6588.cpp
> +const int MAX = 1000000; // 테스트 케이스 및 n의 최대 범위
p3. 상수 선언 좋아요 :3 그런데 MAX가 선언되어 있기는 한데, 코드에서 따로 사용하지는 않으신 것 같아요! 이런 경우에는 그냥 지워주셔도 되겠습니다~

2024-09-08 04:13 UTC, avocado8 commented on 03_정수론/필수/6588.cpp
> +int main(){
와~~~~ 꼼꼼한 주석 너무 좋아요

2024-09-08 04:13 UTC, avocado8 commented on 03_정수론/필수/6588.cpp
> +    findOddPrime(primes, max_n);    // max_n 까지의 홀수 소수 찾아놓기
백만까지의 모든 수가 아닌 입력된 테스트케이스 중에서 가장 큰 수까지만 소수를 찾아주셨네요! 연산 횟수가 적어지겠네요 정말 멋져요 :3

2024-09-09 05:44 UTC, kimeunsom requested changes
(p1) 백준에서 맞았습니다가 뜨지 않는 경우는 과제 제출로 인정되지 않습니다..! 현재 코드는 컴파일 에러가 나고있네요..ㅜㅜ 수정하셔서 리뷰어 다시 호출하시면 다시 리뷰해드리겠습니다 ! 사소한 에러고, 아직 강의 초반이기에 한 번의 유예를 드리지만, 다음부터는 백준에 맞았습니다가 뜨지 않는 경우에는 과제 제출로 인정되지 않는다는 점 유의해주세요 !

2024-09-09 05:44 UTC, kimeunsom commented on 03_정수론/필수/2840.cpp
> +        else if (wheel[ptr] == '?'){
if 문이 없이 else if 가 사용되어 컴파일 에러가 나는 것 같습니다 ..!

2024-09-11 06:45 UTC, ruruisryu reviewed
1735번 너무 잘 풀어주셨습니다! 주석도 깔끔히 잘 달아주셔서 빠르게 리뷰할 수 있었어요. 수고하셨습니다!

2024-09-11 06:45 UTC, ruruisryu commented on 03_정수론/필수/1735.cpp
> +    }
tmp보다는 gcd라는 변수명이 더 적합할 것 같네요! 그 외 변수명들도 좀 더 명확한 이름으로 명명해주시면 좋을 것 같아요~
gcd가 1인 경우에는 ans_a와 ans_b를 gcd로 나눠봤자 나누지 않은 상황과 다를 바 없으니 if 조건이 있든 없든 똑같은 결과를 낼 것 같네요!
```
ans_a /= tmp;
ans_b /= tmp;
```
이 부분만 남겨두어도 괜찮을 것 같습니다. ☺️

2024-09-11 06:45 UTC, ruruisryu commented on 03_정수론/필수/1735.cpp
> +    checkGCF(ans_a, ans_b);
함수화 좋아요~

2024-09-18 07:57 UTC, minae-mina commented on 03_정수론/필수/2840.cpp
@kimeunsom 
안녕하세요. 너무 늦게 확인해서 죄송합니다!! 혹시 괜찮으시다면 확인해 주실 수 있을까요?
또한 혹시 이 경우 3주차 과제는 미제출로 처리된걸로 보면 될까요?
감사합니다.

2024-09-19 14:06 UTC, kimeunsom commented on 03_정수론/필수/2840.cpp
2840 구현 문제 잘 돌아가는 것 확인했습니다 :) 아직 강의 초반이라 과제 제출에 미숙하신 점 고려하여 5문제 모두 잘 제출된 것으로 처리하였습니다 ! 과제 열심히 해주셔서 감사해요 :D

2024-09-20 09:29 UTC, merged